const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);
const ui={lobby:$('lobby'),game:$('gameScreen'),over:$('gameOver'),score:$('score'),lives:$('lives'),level:$('level'),final:$('finalScore'),status:$('connectionStatus'),room:$('roomBox'),panel:$('roomPanel'),action:$('roomActionBtn'),pause:$('pauseOverlay')};
const db=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_KEY);const ICE={iceServers:[{urls:'stun:stun.l.google.com:19302'}]};
let mode='solo',state='lobby',score=0,lives=3,wave=1,enemies=[],bullets=[],players=[],keys={},raf=0,paused=false,last=0,peer=null,channel=null,roomId='',signalChannel=null,answerSeen=false,heartbeatTimer=0;
const say=t=>ui.status.textContent=t, wait=ms=>new Promise(r=>setTimeout(r,ms));
function roomCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
async function signal(kind,payload,sender){const{error}=await db.from('si_signals').insert({room_id:roomId,kind,sender,payload});if(error)throw error}
async function touchRoom(){if(mode!=='host'||!roomId)return;await db.from('si_rooms').update({last_seen_at:new Date().toISOString()}).eq('id',roomId)}
async function closeRoom(){if(mode==='host'&&roomId){clearInterval(heartbeatTimer);await db.from('si_rooms').delete().eq('id',roomId)}}
function watchRoom(){if(signalChannel)return;signalChannel=db.channel('si-room-'+roomId).on('postgres_changes',{event:'INSERT',schema:'public',table:'si_signals',filter:'room_id=eq.'+roomId},async({new:msg})=>{if(msg.sender===mode)return;if(msg.kind==='answer'&&mode==='host'&&!answerSeen){answerSeen=true;await peer.setRemoteDescription(msg.payload);say('Connected to guest. Click START GAME.')} }).subscribe()}
async function waitIce(){if(peer.iceGatheringState==='complete')return;await new Promise(resolve=>{const f=()=>{if(peer.iceGatheringState==='complete'){peer.removeEventListener('icegatheringstatechange',f);resolve()}};peer.addEventListener('icegatheringstatechange',f);setTimeout(resolve,5000)})}
function setupPeer(host){peer=new RTCPeerConnection(ICE);peer.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(peer.connectionState))say('Peer disconnected.')};if(host){channel=peer.createDataChannel('invaders');setupChannel()}else peer.ondatachannel=e=>{channel=e.channel;setupChannel()}}
function setupChannel(){channel.onopen=()=>say('Connected! Two-player co-op ready.');channel.onmessage=e=>{const m=JSON.parse(e.data);if(mode==='host'){if(m.type==='input'&&players[1]){players[1].left=m.left;players[1].right=m.right}if(m.type==='fire')fire(1)}else if(m.type==='state')applyState(m)}}
async function hostGame(){try{mode='host';roomId=roomCode();const roomName=(ui.roomName.value||'Unnamed mission').trim().slice(0,40)||'Unnamed mission';const{error}=await db.from('si_rooms').insert({id:roomId,name:roomName,last_seen_at:new Date().toISOString()});if(error)throw error;setupPeer(true);watchRoom();const offer=await peer.createOffer();await peer.setLocalDescription(offer);await waitIce();await signal('offer',peer.localDescription,'host');ui.room.value=roomId;ui.panel.classList.remove('hidden');heartbeatTimer=setInterval(()=>{touchRoom().catch(()=>{})},30000);ui.action.textContent='WAITING FOR PLAYER';say('Share room ID '+roomId+' with your friend.')}catch(e){say('Could not create room: '+e.message)}}
async function joinGame(){mode='guest';ui.panel.classList.remove('hidden');ui.action.textContent='JOIN';ui.room.focus();say('Enter the room ID shared by the host.')}
async function connectRoom(){try{roomId=ui.room.value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(roomId))throw Error('Enter a valid 6-character room ID.');const{data:room,error}=await db.from('si_rooms').select('id').eq('id',roomId).gt('expires_at',new Date().toISOString()).maybeSingle();if(error||!room)throw Error('Room not found or expired.');setupPeer(false);watchRoom();let offer=null;for(let i=0;i<30&&!offer;i++){const{data}=await db.from('si_signals').select('payload').eq('room_id',roomId).eq('kind','offer').order('created_at',{ascending:false}).limit(1).maybeSingle();offer=data?.payload||null;if(!offer)await wait(500)}if(!offer)throw Error('Host offer not available.');await peer.setRemoteDescription(offer);const answer=await peer.createAnswer();await peer.setLocalDescription(answer);await waitIce();await signal('answer',peer.localDescription,'guest');say('Connected. Waiting for the host to start.')}catch(e){say(e.message)}}
async function copyRoom(){try{await navigator.clipboard.writeText(ui.room.value);say('Room ID copied.')}catch{say('Select the room ID and copy it manually.')}}
function initEnemies(){enemies=[];for(let r=0;r<5;r++)for(let c=0;c<10;c++)enemies.push({x:50+c*60,y:55+r*45,w:40,h:28})}
function startGame(){state='playing';paused=false;score=0;lives=3;wave=1;bullets=[];players=[{x:250,y:545,color:'#50f5a9',left:false,right:false},...(mode==='host'&&channel?[{x:550,y:545,color:'#5cc8ff',left:false,right:false}]:[])];initEnemies();ui.lobby.classList.add('hidden');ui.game.classList.remove('hidden');ui.over.classList.add('hidden');updateUI();cancelAnimationFrame(raf);last=performance.now();raf=requestAnimationFrame(loop)}
function updateUI(){ui.score.textContent=`Score: ${score}`;ui.lives.textContent=`Lives: ${lives}`;ui.level.textContent=`Wave: ${wave}`}
function fire(i=0){if(state!=='playing'||paused||!players[i])return;const p=players[i];if(i===1&&mode==='guest')return;if(bullets.filter(b=>b.owner===i).length>=3)return;bullets.push({x:p.x+21,y:p.y,owner:i})}
function hit(a,b){return a.x<b.x+b.w&&a.x+4>b.x&&a.y<b.y+b.h&&a.y+15>b.y}
function applyState(m){if(state!=='playing')startGame();score=m.score;lives=m.lives;wave=m.wave;enemies=m.enemies;players=m.players;bullets=m.bullets;updateUI()}
function draw(){ctx.fillStyle='#050816';ctx.fillRect(0,0,800,600);enemies.forEach(e=>{ctx.fillStyle='#ff6b9d';ctx.fillRect(e.x,e.y,e.w,e.h);ctx.fillStyle='#050816';ctx.fillRect(e.x+8,e.y+8,6,6);ctx.fillRect(e.x+26,e.y+8,6,6)});players.forEach(p=>{ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,42,20);ctx.fillRect(p.x+14,p.y-10,14,10)});bullets.forEach(b=>{ctx.fillStyle=b.owner?'#5cc8ff':'#50f5a9';ctx.fillRect(b.x,b.y,4,15)})}
function loop(now){if(state!=='playing')return;const dt=Math.min((now-last)/16.67,2);last=now;if(!paused){players.forEach((p,i)=>{if(p.left)p.x=Math.max(0,p.x-7*dt);if(p.right)p.x=Math.min(758,p.x+7*dt)});if(mode==='guest'&&channel?.readyState==='open')channel.send(JSON.stringify({type:'input',left:!!keys.ArrowLeft||!!keys.a,right:!!keys.ArrowRight||!!keys.d}));if(mode==='host'){bullets.forEach(b=>b.y-=10*dt);bullets=bullets.filter(b=>b.y>-20);for(let i=bullets.length-1;i>=0;i--)for(let j=enemies.length-1;j>=0;j--)if(hit(bullets[i],enemies[j])){enemies.splice(j,1);bullets.splice(i,1);score+=10;break}if(!enemies.length){wave++;initEnemies();}if(channel?.readyState==='open')channel.send(JSON.stringify({type:'state',score,lives,wave,enemies,players,bullets}))}draw();updateUI()}raf=requestAnimationFrame(loop)}
function togglePause(){paused=!paused;ui.pause.classList.toggle('hidden',!paused)}
document.addEventListener('keydown',e=>{keys[e.key]=true;if(e.key===' '){e.preventDefault();if(mode==='guest'&&channel?.readyState==='open')channel.send(JSON.stringify({type:'fire'}));else fire(0)}if(e.key.toLowerCase()==='p')togglePause()});document.addEventListener('keyup',e=>keys[e.key]=false);
$('startBtn').onclick=()=>{mode='solo';startGame()};$('hostBtn').onclick=hostGame;$('joinBtn').onclick=joinGame;ui.action.onclick=()=>mode==='guest'?connectRoom():say('Waiting for a guest…');$('copyRoomBtn').onclick=copyRoom;$('instructionsBtn').onclick=()=>$('instructions').classList.remove('hidden');$('closeInstructions').onclick=()=>$('instructions').classList.add('hidden');$('pauseBtn').onclick=togglePause;$('resumeBtn').onclick=togglePause;$('restartBtn').onclick=startGame;$('menuBtn').onclick=()=>location.reload();$('leftBtn').onpointerdown=()=>keys.ArrowLeft=true;$('leftBtn').onpointerup=()=>keys.ArrowLeft=false;$('rightBtn').onpointerdown=()=>keys.ArrowRight=true;$('rightBtn').onpointerup=()=>keys.ArrowRight=false;$('fireBtn').onclick=()=>fire(mode==='guest'?1:0);
window.addEventListener('pagehide',()=>{closeRoom()});
